services:
  - type: web
    name: name-style-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python name_style_bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
    healthCheckPath: /
    autoDeploy: true
    plan: free
    disk:
      name: data
      mountPath: /data
      sizeGB: 1 