services:
  - type: web
    name: name-style-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python render_bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: RENDER_SERVICE_NAME
        sync: false
      - key: PORT
        value: 8080
    healthCheckPath: /
    autoDeploy: true
    plan: free
    disk:
      name: data
      mountPath: /data
      sizeGB: 1 